language: node_js
node_js:
  - "6"
 
branches:
  only:
    - master
 
cache:
  directories:
    - node_modules
 
script:
  - npm run build.prod
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: fe3c6c7a768af4686777d44da2aa3a67d47697bb
  local_dir: dist
  on:
    branch: master
